### ISSUE TITLE
can't type in command line

### ISSUE THREAD

**Issue by ze-or** [apsun/AbsoluteTouch#3]
I am not sure if this my fault but i can't type in the command line

**Comment by apsun** [comment]
Can you give more details on your problem? While the program is running you shouldn't be able to type anything (or rather, your input will be ignored), that's the expected behavior.

**Comment by ze-or** [comment]
hm maybe I am mistaking something. i will change the question. where do i enter the command line argument?

**Comment by apsun** [comment]
When you run the program. So for example, if you are running it from command prompt:

```
AbsoluteTouch.exe -w 50 -t 50,0,100,100
```

If you are using a shortcut, you can put it in the target field in the shortcut properties.

**Comment by ze-or** [comment]
thank you!!
