### ISSUE TITLE
Is this compatible with ASUS touchpads ?

### ISSUE THREAD

**Issue by Trobador** [apsun/AbsoluteTouch#6]
I really wanna try using this for osu!, but the console command window closes instantly after launching the .exe. I thought it might simply be that I don't have the right drivers installed, but I can't even find a download on Synaptics' site. And since I didn't even know if my touchpad was Synaptics, I went to check its driver and found it's called "ASUS Touchpad" with no mention of Synaptics.

Is the dream dead?

**Comment by apsun** [comment]
What is your laptop model? I believe most laptop touchpads are made by either Synaptics or Elan. It could also be that the program just isn't detecting your touchpad correctly (seeing as the program doesn't _crash_ but just exits immediately, this actually sounds pretty likely)

Also if you want to see the output of the program before it quits, you can open command prompt and run AbsoluteTouch from there; the command prompt window should remain open even after AbsoluteTouch exits.

**Comment by Trobador** [comment]
My laptop is an ASUS X751LX.

[This was the output I got from cmd.](https://i.imgur.com/8gadJ0r.png)

**Comment by apsun** [comment]
That error indicates your laptop doesn't have the Synaptics COM libraries installed, which either means you don't have the appropriate drivers or your touchpad isn't made by Synaptics. I looked on ASUS's website and it looks like they use some custom "ASUS Smart Gesture" driver, and from what people are saying it appears to be an Elan touchpad - so unfortunately it's not supported :-(

**Comment by Trobador** [comment]
Ahh, dangit! Well, I expected it anyway. Thank you for making this tool and taking your time to help me. If I ever change laptops, I'll try again!
